"""add column first mentioned

Revision ID: 31fa8cdea418
Revises: 
Create Date: 2022-04-20 20:23:14.631181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fa8cdea418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('first_mentioned', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'first_mentioned')
    # ### end Alembic commands ###
