"""add coordinates

Revision ID: a9c8da7a370f
Revises: effed8b8418c
Create Date: 2022-04-20 20:48:50.420969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c8da7a370f'
down_revision = 'effed8b8418c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('coordinates', sa.String(length=50), nullable=True))
    op.drop_column('cities', 'city_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_name', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('cities', 'coordinates')
    # ### end Alembic commands ###
