"""change name to city name

Revision ID: effed8b8418c
Revises: a353cb9a5e12
Create Date: 2022-04-20 20:42:16.758642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effed8b8418c'
down_revision = 'a353cb9a5e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('city_name', sa.String(length=100), nullable=True))
    op.drop_column('cities', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('cities', 'city_name')
    # ### end Alembic commands ###
