"""delete coordinates

Revision ID: fdfcaf2abbab
Revises: a9c8da7a370f
Create Date: 2022-04-20 20:52:18.121319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfcaf2abbab'
down_revision = 'a9c8da7a370f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('city_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
